### ISSUE TITLE
Suggestion: Function to backup Guilds + Friends to a text file.

### ISSUE THREAD

**Issue by N3xIALIST** [AsjadOooO/Zero-attacker#10]
Function to:

- Backup friends with their username + tag
- Backup joined guilds with the name + invite.

It would be great to be able to do this with both your own account and others using tokens. Imagine if you could just yoink someone's guild invites to troll them. Not that I would use that much, I only need this function to make sure I don't lose my online friends permanently.

**Comment by AsjadOooO** [comment]
Sure will add as we reach 45 stars
