### ISSUE TITLE
PyArmor - Not Load

### ISSUE THREAD

**Issue by KeevoDev** [AsjadOooO/Zero-attacker#11]
when i start the tool and start a module give me error

RuntimeError: Marshal loads failed

**Comment by AsjadOooO** [comment]
Your py error google it

**Comment by AsjadOooO** [comment]
Use python correct version which I'm using 3.9 so it can be compatible with pyarmor

**Comment by KeevoDev** [comment]
> 
> 
> Use python correct version which I'm using 3.9 so it can be compatible with pyarmor

the token gen bypass captcha ? or i can use my 2cap key

**Comment by AsjadOooO** [comment]
nah the code is hided i have already given my private key so dont worr
