### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by linus93** [AsjadOooO/Zero-attacker#15]
After running zero-tool.py, script appeared on Terminal successfully, but when I return the command with number 1-6 it says command not found. I'm running os on vsc.

**Comment by AsjadOooO** [comment]
for me its working fine. try to install https://github.com/AsjadOooO/Zero-attacker/releases/tag/zero-attacker

**Comment by jo9182** [comment]
I have the same issue, I used the download guide on the README.

**Comment by jo9182** [comment]
If I respond with anything other than 6 it does respond with "Please choose the correct one dont be dumb"

**Comment by AsjadOooO** [comment]
add me on discord will explain how to use it Asjad#0060
