### ISSUE TITLE
Clueless

### ISSUE THREAD

**Issue by 6smol** [AsjadOooO/Zero-attacker#16]
i don't know how to run it aslo do i have to download colorama>=0.4.4
discord.py>=1.5.1
pyinstaller
pynput
pyarmor
requests
ipapi
IPy
geocoder
carrier
timezone
bs4
json
hashlib
httpx_socks
urllib
concurrent.futures
oncurrent.futures
pyautogui
pywebcopy
discord.py
pypresence
 all of this? to make it work and do i need python 3.9?

**Comment by AsjadOooO** [comment]
yes and 3.9 above
