### ISSUE TITLE
tHE GEN DOES NOT WORK

### ISSUE THREAD

**Issue by DontCodeTheUnknown** [AsjadOooO/Zero-attacker#17]
THE GEN DOES NOT WORK

**Comment by Casper-dev172** [comment]
this repo virus they use pyarmor so that the virus codes are not visible and they make the codes not visible

**Comment by AsjadOooO** [comment]
We have over 150+ stars used by 1000+ users.
the gen is outdated have some issues would be fixed with new update

**Comment by AsjadOooO** [comment]
> this repo virus they use pyarmor so that the virus codes are not visible and they make the codes not visible

Excuse lol we have over 150+ stars and 1000+ happy users who tried it. code is encrypted to save it from skids like u who copies code and upload on there repo

**Comment by AsjadOooO** [comment]
Code is about to be public once we update everything 
Yes, I can upload it to any hacking forums. But that's my choice u r not the one judging what should I do or not
