### ISSUE TITLE
Nice rat

### ISSUE THREAD

**Issue by Hellscap3d** [AsjadOooO/Zero-attacker#20]
https://www.virustotal.com/gui/file/4d426e3e4f35223ed1b73d8ec6ae1d9d1c83bbdd0ec5a6c0b6e1495ab97b1182

**Comment by H-nta1** [comment]
![image](https://user-images.githubusercontent.com/72767525/157915330-dcaf70ca-bb15-4742-831c-1123f1a36da6.png)

**Comment by H-nta1** [comment]
![image](https://user-images.githubusercontent.com/72767525/157915513-1f12d6e4-c3b2-4101-a7ab-75eeac6f5d50.png)

**Comment by AsjadOooO** [comment]
ofc the virus is gonna triggered by unauthorized software? get some knowledge of files and how it works before posting this ss

**Comment by AsjadOooO** [comment]
can't see anywhere it's our file so keep on making fake bs

**Comment by Hellscap3d** [comment]
> can't see anywhere it's our file so keep on making fake bs

I FUCKING SENT THE LINK, HOW RETARDED ARE YOU?
AND I KNOW FILES, I CODE PY ASWELL.

**Comment by wolfff21123** [comment]
Bro its not malware lol pyinstaller use hook methods to make python runtime run the code without install python xD
