### ISSUE TITLE
open source...

### ISSUE THREAD

**Issue by billythegoat356** [AsjadOooO/Zero-attacker#21]
please understand the purpose of github; OPEN SOURCE
not your pyarmor obfuscated shit

**Comment by AsjadOooO** [comment]
There is a reason behind encrypting the code. We didn't know we would gain these many stars and downloads. So we did protect the code from others. For stealing and using it as their own. 

Me and the other developer who worked on it. Are currently busy with our studies. We aren't working on this project atm. so in May, this repository would no more be obfuscated. 
We understand the concept of GitHub. The purpose behind it is open source project
Just some irl problem didn't let us release the code. Would be soon

**Comment by billythegoat356** [comment]
There are other ways to protect code. If people steal your code (which also happened to me) they wouldn't go far with it since you have so many stars. You could also use a license.
The problem is that by obfuscating the project we cannot know if the code is safe to run or not.

**Comment by 51L3N7-X** [comment]
> please understand the purpose of github; OPEN SOURCE not your pyarmor obfuscated shit

agree with you
