### ISSUE TITLE
THIS IS A VIRUS

### ISSUE THREAD

**Issue by BudderFortress7** [AsjadOooO/Zero-attacker#45]
I looked up the files before I download. All the files has an encrypted (for bypassing the antivirus) hexadecimal code. This is a malicious file. Don't download it

**Comment by Hushhh12** [comment]
I ran it, how do I get rid of virus

**Comment by Blackhole123443** [comment]
run a windows defender scan and try to delete it from files and open ur
prefetch and delete it if not idk

**Comment by Hushhh12** [comment]
I only downloaded it and when I tried running it I got a message saying it was a malicious file but it never fully opened to where everything popped up where I could use it. Do you think I am safe since I never fully ran it and windows defender gave me a prompt stopping me?

**Comment by ppsnipes** [comment]
dumbass, it's a false positive. it's a fucking hacking tool that relies heavily on cmd prompts, and of course it's obfuscated, what did you expect?

**Comment by Blackhole123443** [comment]
Well I didn’t download it for a reason. I didn’t download it because I
didn’t know what python version I should use
