### ISSUE TITLE
DONT DOWNLOAD THIS! ITS VIRUS

### ISSUE THREAD

**Issue by vollehax** [AsjadOooO/Zero-attacker#47]
After downloading this and opening few times it gives error and after all that my internet will start getting down and bad
I HAVE NOT DOWNLOADED AND OPENED ANY OTHER FILES FROM GITHUB ONLY THIS!
SO its stressing your net. DO NOT DOWNLOAD

**Comment by AsjadOooO** [comment]
it's not a virus , code isn't been updated for 2-3 years you can join the server check the source code yourself
