### ISSUE TITLE
Guys Don't Be Idiots

### ISSUE THREAD

**Issue by Albuman** [AsjadOooO/Zero-attacker#48]
First of it is impossible to generate tokens the is like a chance of 1 in a 10000000000 that you will get one.

This file contains a credit cards stealer, password and a token stealer.
DO NOT RUN THIS ON YOUR COMPUTER!! It will just open cmd and your done!!

**Comment by Albuman** [comment]
**Please don't be stupid**

**Comment by ClippyGotchu** [comment]
oh, shit

**Comment by ClippyGotchu** [comment]
Why did I not read the fucking code

**Comment by ClippyGotchu** [comment]
Wtf do I do

**Comment by Figo579** [comment]
Change your passwords

**Comment by AsjadOooO** [comment]
it's not a virus , code isn't been updated for 2-3 years you can join the server check the source code yourself

**Comment by AlbumanO** [comment]
Then why is the whole f'ing thing obfuscated SO WE CANT SEE THE CODE I don't see how this is open scammer
